create TABLE IF NOT EXISTS chat
(
    id BIGINT PRIMARY KEY
);

create TABLE IF NOT EXISTS link
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(1024) NOT NULL,
    updated TIMESTAMPTZ DEFAULT NOW(),
	CONSTRAINT uc_url UNIQUE (url)
);

create TABLE IF NOT EXISTS chat_link
(
    chat_id BIGINT,
    link_id BIGINT,
	CONSTRAINT pk_chat_link PRIMARY KEY (chat_id, link_id),
	CONSTRAINT fk_chat_link_chat_id FOREIGN KEY(chat_id) REFERENCES chat(id) ON delete CASCADE,
	CONSTRAINT fk_chat_link_link_id FOREIGN KEY(link_id) REFERENCES link(id) ON delete CASCADE
);