name: Scrapper module

on:
  push:
    paths:
      - 'scrapper/**'
      - .github/workflows/scrapper.yml

  pull_request:
    paths:
      - 'scrapper/**'

env:
  REGISTRY: ghcr.io
  USERNAME: pa11ady

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Maven package
        run: mvn package -pl scrapper -am

      - name: Build  image
        run: docker build scrapper/ -t $REGISTRY/$USERNAME/scrapper:latest

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push $REGISTRY/$USERNAME/scrapper:latest

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run Checkstyle
        run: mvn -pl scrapper -am checkstyle:check